FROM python:3.8
ADD src/python/container/container.py .
ADD data/routing.json .
ADD src/python/container/cloud_interface.py .
RUN pip install flask
RUN pip install bash
RUN pip install docker
ENTRYPOINT ["python3", "container.py"]
